# Generated by Django 2.2.12 on 2020-04-27 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0002_auto_20200425_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
        migrations.RenameModel(
            old_name='Consultations',
            new_name='Consultation',
        ),
        migrations.RenameModel(
            old_name='Prescriptions',
            new_name='Prescription',
        ),
    ]
