# Generated by Django 2.2.12 on 2020-04-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_auto_20200427_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_desc',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
